In [2]:
import torch
device = "cuda" if torch.cuda.is_available() else "cpu"
my_tensor = torch.tensor([[1,2,3],[4,5,6]], dtype = torch.float32, device = device, requires_grad=True)
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)


In [3]:
print (my_tensor.dtype)
print(my_tensor.device)
print (my_tensor.shape)
print(my_tensor.requires_grad)

torch.float32
cuda:0
torch.Size([2, 3])
True


In [4]:
# Other common initaliation methods
print(torch.empty(size=(3,3)))
print (torch.zeros((3,3)))
x = torch.rand((3,3))
print(x)
print (torch.eye(5,5))
print (torch.arange(5,10,2))
print (torch.linspace(5,10,10))
print (torch.empty(size=(2,2)).normal_(mean=0,std=0.5))
print (torch.empty(size=(2,2)).uniform_(0,1))
print (torch.diag(x))
tensor = torch.arange(0,10,2)
print (tensor)
print(tensor.bool())

tensor([[-1.1262e-36,  3.0694e-41,  3.3631e-44],
        [ 0.0000e+00,         nan,  3.0694e-41],
        [ 1.1578e+27,  1.1362e+30,  7.1547e+22]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.1694, 0.8536, 0.1256],
        [0.8731, 0.9670, 0.3602],
        [0.3059, 0.7561, 0.2020]])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([5, 7, 9])
tensor([ 5.0000,  5.5556,  6.1111,  6.6667,  7.2222,  7.7778,  8.3333,  8.8889,
         9.4444, 10.0000])
tensor([[-0.5656, -0.2832],
        [-0.2987, -0.0538]])
tensor([[0.8426, 0.3511],
        [0.0679, 0.1224]])
tensor([0.1694, 0.9670, 0.2020])
tensor([0, 2, 4, 6, 8])
tensor([False,  True,  True,  True,  True])


In [5]:
print(tensor.short())

tensor([0, 2, 4, 6, 8], dtype=torch.int16)


In [6]:
print(tensor.half())

tensor([0., 2., 4., 6., 8.], dtype=torch.float16)


In [7]:
print (tensor.float())
print (tensor.double())

tensor([0., 2., 4., 6., 8.])
tensor([0., 2., 4., 6., 8.], dtype=torch.float64)


In [8]:
import numpy as np 
n_before = np.random.rand(3,4)
print(n_before)
n_tensor = torch.from_numpy(n_before)
print(n_tensor)
n_after = n_tensor.numpy ()
print(n_after)


[[0.58948785 0.61750099 0.31285074 0.6188802 ]
 [0.82082015 0.78307627 0.52955646 0.79323223]
 [0.1095466  0.40303546 0.31761389 0.91070038]]
tensor([[0.5895, 0.6175, 0.3129, 0.6189],
        [0.8208, 0.7831, 0.5296, 0.7932],
        [0.1095, 0.4030, 0.3176, 0.9107]], dtype=torch.float64)
[[0.58948785 0.61750099 0.31285074 0.6188802 ]
 [0.82082015 0.78307627 0.52955646 0.79323223]
 [0.1095466  0.40303546 0.31761389 0.91070038]]


In [9]:
x = torch.tensor([1,2,4])
y = torch.tensor([1,2,4])
print(x+y)
print(torch.add(x,y))
print(torch.mul(x,y))
print(torch.div(x,y))
print(torch.true_divide(x,y))

tensor([2, 4, 8])
tensor([2, 4, 8])
tensor([ 1,  4, 16])
tensor([1., 1., 1.])
tensor([1., 1., 1.])


In [10]:
# Inplace operation (fjd_)
t = torch.ones(3)
print(t+x)
print(t.add_(x)) # It adds and replaces the content
print(t+x) # t+ = x == this is also inplace

tensor([2., 3., 5.])
tensor([2., 3., 5.])
tensor([3., 5., 9.])


In [11]:
print(x.pow(2))
print(x**2)

tensor([ 1,  4, 16])
tensor([ 1,  4, 16])


In [12]:
print (x<y)
print (y>0)
print (x==y)
print (x>=y)

tensor([False, False, False])
tensor([True, True, True])
tensor([True, True, True])
tensor([True, True, True])


In [13]:
x1 = torch.rand((2,5))
x2 = torch.rand((5,3))
print(torch.mm(x1,x2))
print(x1.mm(x2))
print(torch.dot(x,y))
print(x.dot(y))

tensor([[0.8146, 1.0658, 0.8748],
        [1.4652, 1.8327, 1.4053]])
tensor([[0.8146, 1.0658, 0.8748],
        [1.4652, 1.8327, 1.4053]])
tensor(21)
tensor(21)


In [14]:
# Batch matrix multiplicatin
batch =32
n=10
m=20
p=30

tensor1= torch.rand(batch,n,m)
tensor2= torch.rand(batch,m,p)
bmm = torch.bmm(tensor1,tensor2)

In [20]:
# Broadcasting
x1 = torch.rand((3,5))
x2 = torch.rand ((1,5))

print(x1)
print(x2)
print(x2*x1)

tensor([[0.0723, 0.8680, 0.8546, 0.9561, 0.0031],
        [0.7587, 0.7328, 0.4957, 0.8305, 0.8993],
        [0.7017, 0.8334, 0.3705, 0.6394, 0.6946]])
tensor([[0.3329, 0.1564, 0.3119, 0.4631, 0.2688]])
tensor([[0.0241, 0.1358, 0.2665, 0.4428, 0.0008],
        [0.2526, 0.1146, 0.1546, 0.3846, 0.2417],
        [0.2336, 0.1304, 0.1155, 0.2961, 0.1867]])


In [30]:
# Other useful operations
sum_x  =torch.sum(x1)
sum_x_dim0  =torch.sum(x1, dim=0)
sum_x_dim1  =torch.sum(x1, dim=1)
print(sum_x)
print(sum_x_dim0)
print(sum_x_dim1)

tensor(9.7105)
tensor([1.5327, 2.4342, 1.7207, 2.4260, 1.5970])
tensor([2.7540, 3.7170, 3.2395])


In [38]:
max_x = torch.max(x1)
max_x_dim0 = torch.max(x1, dim=0)
max_x_dim1 = torch.max(x1, dim=1)
print(max_x)
print(max_x_dim0)
print(max_x_dim1)

val, ind = torch.max(x1, dim=0)
print(val)
print(ind)

tensor(0.9561)
torch.return_types.max(
values=tensor([0.7587, 0.8680, 0.8546, 0.9561, 0.8993]),
indices=tensor([1, 0, 0, 0, 1]))
torch.return_types.max(
values=tensor([0.9561, 0.8993, 0.8334]),
indices=tensor([3, 4, 1]))
tensor([0.7587, 0.8680, 0.8546, 0.9561, 0.8993])
tensor([1, 0, 0, 0, 1])


In [47]:
# Can use dimension attribute for rows and column
print(torch.abs(x1))
print(torch.argmax(x1))
print(torch.argmin(x1))
print(torch.mean(x1))
print(torch.mean(x1, dim=0))
print(torch.std(x1))
print(torch.var(x1))

tensor([[0.0723, 0.8680, 0.8546, 0.9561, 0.0031],
        [0.7587, 0.7328, 0.4957, 0.8305, 0.8993],
        [0.7017, 0.8334, 0.3705, 0.6394, 0.6946]])
tensor(3)
tensor(4)
tensor(0.6474)
tensor([0.5109, 0.8114, 0.5736, 0.8087, 0.5323])
tensor(0.2914)
tensor(0.0849)


In [52]:
print (torch.sort(x1, descending=True, dim=0))

torch.return_types.sort(
values=tensor([[0.7587, 0.8680, 0.8546, 0.9561, 0.8993],
        [0.7017, 0.8334, 0.4957, 0.8305, 0.6946],
        [0.0723, 0.7328, 0.3705, 0.6394, 0.0031]]),
indices=tensor([[1, 0, 0, 0, 1],
        [2, 2, 1, 1, 2],
        [0, 1, 2, 2, 0]]))


In [54]:
# clamp
z = torch.tensor([-1,0,4,5,10,7,-6,22,33])
print(torch.clamp(z, min=0, max=10,)) # Basically like RELU function
# anything below zero will be set to 0 and anything above 10 will be set to 10

tensor([ 0,  0,  4,  5, 10,  7,  0, 10, 10])


In [57]:
bool_val = torch.tensor([1,0,0,1,1,0], dtype=torch.bool)
print(bool_val)
print(torch.any(bool_val))
print(torch.all(bool_val))

tensor([ True, False, False,  True,  True, False])
tensor(True)
tensor(False)
